extends:
  - appnexus/frontend
  - appnexus/typescript

parserOptions:
  project: './tsconfig.json'

rules: 
  '@typescript-eslint/camelcase': off

  # TODO: The following rules were disabled during migration to eslint-appnexus-config
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/member-ordering': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-shadow': off
  '@typescript-eslint/no-unnecessary-type-assertion': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/restrict-plus-operands': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/type-annotation-spacing': off
  import/imports-first: off
  import/no-unresolved: off
  react-hooks/exhaustive-deps: off
  react/jsx-curly-brace-presence: off
  react/prefer-stateless-function: off
