import React from 'react';
import createClass from 'create-react-class';
import { StickySection } from '../../../index';

export default createClass({
	render() {
		return (
			<section
				style={{
					color: 'rgba(128,128,128,.25)',
					marginBottom: 700,
				}}
			>
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				<StickySection style={{ backgroundColor: '#2abbb0', color: 'white' }}>
					This section has no lower bounds!
				</StickySection>
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
				Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray.
			</section>
		);
	},
});
