import React from 'react';
import _ from 'lodash';
import StickySection from '../StickySection';

export default React.createClass({
	render() {
		return(
			<section style={{
				width: 300,
				//height: 300,
				overflow: 'auto',
			}}>
				<section style={{
					width: 700
				}}>
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					<StickySection viewportWidth={300} style={{ backgroundColor: '#2abbb0', color: 'white' }}>I am sooooo sticky...</StickySection>
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
					Post-ironic health goth austin mixtape mlkshk. Cold-pressed ennui messenger bag viral migas. Artisan freegan cold-pressed offal, flexitarian shabby chic polaroid banjo four dollar toast four loko williamsburg. Taxidermy ramps fap vegan bushwick pug, kickstarter scenester actually cornhole locavore man bun chambray. 
				</section>
			</section>
		);
	}
});
