import React from 'react';
import createClass from 'create-react-class';
import { SingleSelect } from '../../../index';

const { Placeholder, Option } = SingleSelect;

export default createClass({
	render() {
		return (
			<section>

				<SingleSelect maxMenuHeight="12em">
					<Placeholder>Select Color</Placeholder>
					<Option>Aliceblue</Option>
					<Option>Antiquewhite</Option>
					<Option>Aqua</Option>
					<Option>Aquamarine</Option>
					<Option>Azure</Option>
					<Option>Beige</Option>
					<Option>Bisque</Option>
					<Option>Black</Option>
					<Option>Blanchedalmond</Option>
					<Option>Blue</Option>
					<Option>Blueviolet</Option>
					<Option>Brown</Option>
					<Option>Burlywood</Option>
					<Option>Cadetblue</Option>
					<Option>Chartreuse</Option>
					<Option>Chocolate</Option>
					<Option>Coral</Option>
					<Option>Cornflowerblue</Option>
					<Option>Cornsilk</Option>
					<Option>Crimson</Option>
					<Option>Cyan</Option>
					<Option>Darkblue</Option>
					<Option>Darkcyan</Option>
					<Option>Darkgoldenrod</Option>
					<Option>Darkgray</Option>
					<Option>Darkgreen</Option>
					<Option>Darkkhaki</Option>
					<Option>Darkmagenta</Option>
					<Option>Darkolivegreen</Option>
					<Option>Darkorange</Option>
					<Option>Darkorchid</Option>
					<Option>Darkred</Option>
					<Option>Darksalmon</Option>
					<Option>Darkseagreen</Option>
					<Option>Darkslateblue</Option>
					<Option>Darkslategray</Option>
					<Option>Darkturquoise</Option>
					<Option>Darkviolet</Option>
					<Option>Deeppink</Option>
					<Option>Deepskyblue</Option>
					<Option>Dimgray</Option>
					<Option>Dodgerblue</Option>
					<Option>Firebrick</Option>
					<Option>Floralwhite</Option>
					<Option>Forestgreen</Option>
					<Option>Fuchsia</Option>
					<Option>Gainsboro</Option>
					<Option>Ghostwhite</Option>
					<Option>Gold</Option>
					<Option>Goldenrod</Option>
					<Option>Gray</Option>
					<Option>Green</Option>
					<Option>Greenyellow</Option>
					<Option>Honeydew</Option>
					<Option>Hotpink</Option>
					<Option>Indianred</Option>
					<Option>Indigo</Option>
					<Option>Ivory</Option>
					<Option>Khaki</Option>
					<Option>Lavender</Option>
					<Option>Lavenderblush</Option>
					<Option>Lawngreen</Option>
					<Option>Lemonchiffon</Option>
					<Option>Lightblue</Option>
					<Option>Lightcoral</Option>
					<Option>Lightcyan</Option>
					<Option>Lightgoldenrodyellow</Option>
					<Option>Lightgray</Option>
					<Option>Lightgreen</Option>
					<Option>Lightpink</Option>
					<Option>Lightsalmon</Option>
					<Option>Lightseagreen</Option>
					<Option>Lightskyblue</Option>
					<Option>Lightslategray</Option>
					<Option>Lightsteelblue</Option>
					<Option>Lightyellow</Option>
					<Option>Lime</Option>
					<Option>Limegreen</Option>
					<Option>Linen</Option>
					<Option>Magenta</Option>
					<Option>Maroon</Option>
					<Option>Medium aquamarine</Option>
					<Option>Mediumblue</Option>
					<Option>Mediumorchid</Option>
					<Option>Mediumpurple</Option>
					<Option>Mediumseagreen</Option>
					<Option>Mediumslateblue</Option>
					<Option>Mediumspringgreen</Option>
					<Option>Mediumturquoise</Option>
					<Option>Mediumvioletred</Option>
					<Option>Midnightblue</Option>
					<Option>Mintcream</Option>
					<Option>Mistyrose</Option>
					<Option>Moccasin</Option>
					<Option>Navajowhite</Option>
					<Option>Navy</Option>
					<Option>Oldlace</Option>
					<Option>Olive</Option>
					<Option>Olivedrab</Option>
					<Option>Orange</Option>
					<Option>Orangered</Option>
					<Option>Orchid</Option>
					<Option>Palegoldenrod</Option>
					<Option>Palegreen</Option>
					<Option>Paleturquoise</Option>
					<Option>Palevioletred</Option>
					<Option>Papayawhip</Option>
					<Option>Peachpuff</Option>
					<Option>Peru</Option>
					<Option>Pink</Option>
					<Option>Plum</Option>
					<Option>Powderblue</Option>
					<Option>Purple</Option>
					<Option>Rebeccapurple</Option>
					<Option>Red</Option>
					<Option>Rosybrown</Option>
					<Option>Royalblue</Option>
					<Option>Saddlebrown</Option>
					<Option>Salmon</Option>
					<Option>Sandybrown</Option>
					<Option>Seagreen</Option>
					<Option>Seashell</Option>
					<Option>Sienna</Option>
					<Option>Silver</Option>
					<Option>Skyblue</Option>
					<Option>Slateblue</Option>
					<Option>Slategray</Option>
					<Option>Snow</Option>
					<Option>Springgreen</Option>
					<Option>Steelblue</Option>
					<Option>Tan</Option>
					<Option>Teal</Option>
					<Option>Thistle</Option>
					<Option>Tomato</Option>
					<Option>Turquoise</Option>
					<Option>Violet</Option>
					<Option>Wheat</Option>
					<Option>White</Option>
					<Option>Whitesmoke</Option>
					<Option>Yellow</Option>
					<Option>Yellowgreen</Option>
				</SingleSelect>

			</section>
		);
	},
});
